# Generated by Django 5.0.2 on 2024-02-26 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_produitc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCde', models.DateField(default=datetime.date(2024, 2, 26), null=True)),
                ('totalCde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('produit', models.ManyToManyField(to='magasin.produit')),
            ],
        ),
    ]
